### ISSUE TITLE
show candidates in rankings for facemash

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/h4i-recruitment#105]
this page should show the rankings of the candidates based on the current matches. This would mainly be used once facemash is over and we decide on who we should interview. 

Ideally, you would also show the total number of matches, and have the number of matches per candidate right next to their name. Each candidate should also be linkable (the link should go to their candidate page like `/candidate?id=5abf3dcf1d567955609d2b9c` where `5abf.....` is the id. 

Other than that, this is pretty open on what you would like to add.

**Comment by angadgarg25** [comment]
Can be added to main page, closing and opened #106
