### ISSUE TITLE
Candidates Page & keys

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/h4i-recruitment#20]
includes #9, #10, #17 
- adding interviews form will include a lot of things, look at the rubric 
- build key pages and backend verification
- work with candidates to generate categories
- split off and work with candidates list page team + facemash team
- easily show the state of a candidate (whether they are declined/accepted/pending/etc)
Remember that this page should look different before interviews, after interviews, during/after deliberations and decisions.
- show data from facemash

**Comment by HRimaw2** [comment]
Candidates Page & keys #20 Breakdown

https://docs.google.com/document/d/1lnRazAewcm25Gf6idaGMm-AHDPMPbLbtlvuh41ln1TQ/edit

**Comment by tko22** [comment]
I love it :)

**Comment by tko22** [comment]
for the interview form, something you could do is add Form Validation if you have time. https://reactstrap.github.io/components/form/#app Scroll down a bit
