### ISSUE TITLE
Designing block for each profile

### ISSUE THREAD

**Issue by CodeBrew28** [hack4impact-uiuc/h4i-recruitment#24]
This should include their: 

Name
Role
Major
The year they started college 
Github Activity (1-5 Ranking) 
Resume/Website (Clickable links)
Experience Ranking (done on application)

+ color code by status

**Comment by tko22** [comment]
remember that this will be heavily used when we go through deliberations, meaning there will be extra information such as their facemash ranking, W/L ratio, etc (data angad & roy decide to track). In addition, the category that their interviewers put the candidate in along with their points, etc will also be there. Discuss with the other teams what might be the best data to show. There are 3 different states (before facemash(cutting down to N number of people), before interview (interviewing stage), after interview(deliberations))
