### ISSUE TITLE
Backend for register & login workflow

### ISSUE THREAD

**Issue by n3a9** [hack4impact-uiuc/h4i-recruitment#262]
Set up the backend for the registering and login workflows in the tool.

https://my-docz-project-codebrew28.hack4impact1.now.sh/register-and-login-workflow

**Comment by caiyingshen** [comment]
we should create a new Mongo table to record the new accounts, their corresponding tokens, and roles. In order to get a profile and the role it has, we need the token to get that information from the PI server.
