### ISSUE TITLE
Backend tests timing out

### ISSUE THREAD

**Issue by arpanlaha** [hack4impact-uiuc/h4i-recruitment#265]
After my last PR (#261), our backend tests are failing due a timeout. We thought this was due to either the new version of mongoose my PR introduced or the `useNewUrlParser` flag I passed in to `backend/src/index.js`, but reverting to the previous commit (`39206a4`) and downgrading mongoose to the previous version also results in the same timeout.

**Comment by n3a9** [comment]
Not sure why it was merged when the tests were failing - https://circleci.com/gh/hack4impact-uiuc/h4i-recruitment/2481

**Comment by arpanlaha** [comment]
@n3a9 It's not a direct result of the changes in the PR, I've thoroughly tested but if you can confirm running on commit `39206a4` then we can be sure.
Maybe an updated dependency that we don't have direct control over?

**Comment by n3a9** [comment]
<img width="1023" alt="Screen Shot 2019-06-27 at 10 03 55 PM" src="https://user-images.githubusercontent.com/7104017/60318348-88d5d480-9927-11e9-92e9-5d26535b02ce.png">

If tests are failing in a PR, it shouldn't be merged. Even though it is not direct result of *changes* in PR, it is direct result of PR.
